Do not destroy the memory step on error
The destroy needs to be called on fini, not here. If we do it here the
fini that will be called later would do nothing (and throw an error).

error: called without a previous init. This shouldn't happen!

Bug 12160